### ISSUE TITLE
Didn't aware of string.join and os.path.join

### ISSUE THREAD

**Issue by azzamsa** [coetaur0/staticfg#6]
```python

$ python3 examples/build_cfg.py /home/user/code-coba-home/manual-compile/staticfg/foo.py /home/user/code-coba-home/manual-compile/staticfg/
Traceback (most recent call last):
  File "examples/build_cfg.py", line 15, in <module>
    cfg = CFGBuilder().build_from_file(cfg_name, args.input_file)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 384, in visit_FunctionDef
    self.new_functionCFG(node, asynchr=False)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 201, in new_functionCFG
    self.current_id)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 310, in visit_If
    self.visit(child)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 264, in visit_Assign
    self.generic_visit(node)
  File "/usr/lib/python3.5/ast.py", line 255, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 259, in visit_Call
    func_name = visit_func(func)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/staticfg/builder.py", line 255, in visit_func
    func_name += "." + node.attr
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by JJK96** [comment]
@azzamsa I have a similar issue but I don't use `join`, how did you debug this?

**Comment by coetaur0** [comment]
Hi, sorry for the late reply. I have updated a new version of the package that corrects the error you were getting. Try `pip install --upgrade staticfg` or `pip install --upgrade .` from the repository's root after pulling from it to install the latest version. The package should now work with your code.

**Comment by JJK96** [comment]
Hi, thx for replying!
I updated to version 0.9.4, but my issue is not fixed, so it's probably something else. 
Do you have any pointers on how I might debug this?

```
python ~/git/staticfg/examples/build_cfg.py ./template.py template.dot
Traceback (most recent call last):
  File "/home/jjk/git/staticfg/examples/build_cfg.py", line 15, in <module>
    cfg = CFGBuilder().build_from_file(cfg_name, args.input_file)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 124, in build_from_file
    return self.build_from_src(name, src)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 108, in build_from_src
    return self.build(name, tree)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 92, in build
    self.visit(tree)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 270, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 268, in visit_Assign
    self.generic_visit(node)
  File "/usr/lib/python3.7/ast.py", line 272, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 272, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 263, in visit_Call
    func_name = visit_func(func)
  File "/usr/lib/python3.7/site-packages/staticfg/builder.py", line 255, in visit_func
    func_name += "." + node.attr
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by azzamsa** [comment]
> @azzamsa I have a similar issue but I don't use `join`, how did you debug this?

@JJK96 Since I just have a small code. I tried to compile them incrementally, till I find the error. (not effective for a big chunk of code)

**Comment by JJK96** [comment]
Thanks @azzamsa I found the origin of my problem, I reported in #8
